# Generated by Django 2.0.6 on 2018-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
